/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/_admin'
import { Route as AdminIndexImport } from './routes/_admin/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AdminProfileImport } from './routes/_admin/profile'
import { Route as AdminAboutImport } from './routes/_admin/about'
import { Route as AdminUserIndexImport } from './routes/_admin/user/index'
import { Route as AdminRoleIndexImport } from './routes/_admin/role/index'
import { Route as AdminProductIndexImport } from './routes/_admin/product/index'
import { Route as AdminFileIndexImport } from './routes/_admin/file/index'
import { Route as AdminCategoryIndexImport } from './routes/_admin/category/index'
import { Route as AdminUserIdImport } from './routes/_admin/user/$id'
import { Route as AdminRoleNewImport } from './routes/_admin/role/new'
import { Route as AdminRoleIdImport } from './routes/_admin/role/$id'
import { Route as AdminProductCreateImport } from './routes/_admin/product/create'
import { Route as AdminProductIdImport } from './routes/_admin/product/$id'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminProfileRoute = AdminProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAboutRoute = AdminAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)

const AdminUserIndexRoute = AdminUserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminRoleIndexRoute = AdminRoleIndexImport.update({
  id: '/role/',
  path: '/role/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminProductIndexRoute = AdminProductIndexImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminFileIndexRoute = AdminFileIndexImport.update({
  id: '/file/',
  path: '/file/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCategoryIndexRoute = AdminCategoryIndexImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminUserIdRoute = AdminUserIdImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => AdminRoute,
} as any)

const AdminRoleNewRoute = AdminRoleNewImport.update({
  id: '/role/new',
  path: '/role/new',
  getParentRoute: () => AdminRoute,
} as any)

const AdminRoleIdRoute = AdminRoleIdImport.update({
  id: '/role/$id',
  path: '/role/$id',
  getParentRoute: () => AdminRoute,
} as any)

const AdminProductCreateRoute = AdminProductCreateImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => AdminRoute,
} as any)

const AdminProductIdRoute = AdminProductIdImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_admin/about': {
      id: '/_admin/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AdminAboutImport
      parentRoute: typeof AdminImport
    }
    '/_admin/profile': {
      id: '/_admin/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AdminProfileImport
      parentRoute: typeof AdminImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/product/$id': {
      id: '/_admin/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof AdminProductIdImport
      parentRoute: typeof AdminImport
    }
    '/_admin/product/create': {
      id: '/_admin/product/create'
      path: '/product/create'
      fullPath: '/product/create'
      preLoaderRoute: typeof AdminProductCreateImport
      parentRoute: typeof AdminImport
    }
    '/_admin/role/$id': {
      id: '/_admin/role/$id'
      path: '/role/$id'
      fullPath: '/role/$id'
      preLoaderRoute: typeof AdminRoleIdImport
      parentRoute: typeof AdminImport
    }
    '/_admin/role/new': {
      id: '/_admin/role/new'
      path: '/role/new'
      fullPath: '/role/new'
      preLoaderRoute: typeof AdminRoleNewImport
      parentRoute: typeof AdminImport
    }
    '/_admin/user/$id': {
      id: '/_admin/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof AdminUserIdImport
      parentRoute: typeof AdminImport
    }
    '/_admin/category/': {
      id: '/_admin/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof AdminCategoryIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/file/': {
      id: '/_admin/file/'
      path: '/file'
      fullPath: '/file'
      preLoaderRoute: typeof AdminFileIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/product/': {
      id: '/_admin/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AdminProductIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/role/': {
      id: '/_admin/role/'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof AdminRoleIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/user/': {
      id: '/_admin/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AdminUserIndexImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductIdRoute: typeof AdminProductIdRoute
  AdminProductCreateRoute: typeof AdminProductCreateRoute
  AdminRoleIdRoute: typeof AdminRoleIdRoute
  AdminRoleNewRoute: typeof AdminRoleNewRoute
  AdminUserIdRoute: typeof AdminUserIdRoute
  AdminCategoryIndexRoute: typeof AdminCategoryIndexRoute
  AdminFileIndexRoute: typeof AdminFileIndexRoute
  AdminProductIndexRoute: typeof AdminProductIndexRoute
  AdminRoleIndexRoute: typeof AdminRoleIndexRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductIdRoute: AdminProductIdRoute,
  AdminProductCreateRoute: AdminProductCreateRoute,
  AdminRoleIdRoute: AdminRoleIdRoute,
  AdminRoleNewRoute: AdminRoleNewRoute,
  AdminUserIdRoute: AdminUserIdRoute,
  AdminCategoryIndexRoute: AdminCategoryIndexRoute,
  AdminFileIndexRoute: AdminFileIndexRoute,
  AdminProductIndexRoute: AdminProductIndexRoute,
  AdminRoleIndexRoute: AdminRoleIndexRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AdminRouteWithChildren
  '/about': typeof AdminAboutRoute
  '/profile': typeof AdminProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AdminIndexRoute
  '/product/$id': typeof AdminProductIdRoute
  '/product/create': typeof AdminProductCreateRoute
  '/role/$id': typeof AdminRoleIdRoute
  '/role/new': typeof AdminRoleNewRoute
  '/user/$id': typeof AdminUserIdRoute
  '/category': typeof AdminCategoryIndexRoute
  '/file': typeof AdminFileIndexRoute
  '/product': typeof AdminProductIndexRoute
  '/role': typeof AdminRoleIndexRoute
  '/user': typeof AdminUserIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AdminAboutRoute
  '/profile': typeof AdminProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AdminIndexRoute
  '/product/$id': typeof AdminProductIdRoute
  '/product/create': typeof AdminProductCreateRoute
  '/role/$id': typeof AdminRoleIdRoute
  '/role/new': typeof AdminRoleNewRoute
  '/user/$id': typeof AdminUserIdRoute
  '/category': typeof AdminCategoryIndexRoute
  '/file': typeof AdminFileIndexRoute
  '/product': typeof AdminProductIndexRoute
  '/role': typeof AdminRoleIndexRoute
  '/user': typeof AdminUserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/about': typeof AdminAboutRoute
  '/_admin/profile': typeof AdminProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/product/$id': typeof AdminProductIdRoute
  '/_admin/product/create': typeof AdminProductCreateRoute
  '/_admin/role/$id': typeof AdminRoleIdRoute
  '/_admin/role/new': typeof AdminRoleNewRoute
  '/_admin/user/$id': typeof AdminUserIdRoute
  '/_admin/category/': typeof AdminCategoryIndexRoute
  '/_admin/file/': typeof AdminFileIndexRoute
  '/_admin/product/': typeof AdminProductIndexRoute
  '/_admin/role/': typeof AdminRoleIndexRoute
  '/_admin/user/': typeof AdminUserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/product/$id'
    | '/product/create'
    | '/role/$id'
    | '/role/new'
    | '/user/$id'
    | '/category'
    | '/file'
    | '/product'
    | '/role'
    | '/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/product/$id'
    | '/product/create'
    | '/role/$id'
    | '/role/new'
    | '/user/$id'
    | '/category'
    | '/file'
    | '/product'
    | '/role'
    | '/user'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/about'
    | '/_admin/profile'
    | '/auth/login'
    | '/auth/register'
    | '/_admin/'
    | '/_admin/product/$id'
    | '/_admin/product/create'
    | '/_admin/role/$id'
    | '/_admin/role/new'
    | '/_admin/user/$id'
    | '/_admin/category/'
    | '/_admin/file/'
    | '/_admin/product/'
    | '/_admin/role/'
    | '/_admin/user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_admin",
        "/auth/login",
        "/auth/register"
      ]
    },
    "/_admin": {
      "filePath": "_admin.tsx",
      "children": [
        "/_admin/about",
        "/_admin/profile",
        "/_admin/",
        "/_admin/product/$id",
        "/_admin/product/create",
        "/_admin/role/$id",
        "/_admin/role/new",
        "/_admin/user/$id",
        "/_admin/category/",
        "/_admin/file/",
        "/_admin/product/",
        "/_admin/role/",
        "/_admin/user/"
      ]
    },
    "/_admin/about": {
      "filePath": "_admin/about.tsx",
      "parent": "/_admin"
    },
    "/_admin/profile": {
      "filePath": "_admin/profile.tsx",
      "parent": "/_admin"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/_admin/": {
      "filePath": "_admin/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/product/$id": {
      "filePath": "_admin/product/$id.tsx",
      "parent": "/_admin"
    },
    "/_admin/product/create": {
      "filePath": "_admin/product/create.tsx",
      "parent": "/_admin"
    },
    "/_admin/role/$id": {
      "filePath": "_admin/role/$id.tsx",
      "parent": "/_admin"
    },
    "/_admin/role/new": {
      "filePath": "_admin/role/new.tsx",
      "parent": "/_admin"
    },
    "/_admin/user/$id": {
      "filePath": "_admin/user/$id.tsx",
      "parent": "/_admin"
    },
    "/_admin/category/": {
      "filePath": "_admin/category/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/file/": {
      "filePath": "_admin/file/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/product/": {
      "filePath": "_admin/product/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/role/": {
      "filePath": "_admin/role/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/user/": {
      "filePath": "_admin/user/index.tsx",
      "parent": "/_admin"
    }
  }
}
ROUTE_MANIFEST_END */
